Be more aggressive when checking if a log message should be sent to the underlying logger
sbt/util pull request #131
Opened 2017-11-07 08:53 UTC by leonardehrenfried

https://github.com/sbt/sbt/issues/3711 hast shown that substantial amount of time is spent calculating log messages that are unlikely to be displayed.

This PR introduces checks that filter out log events for disabled log levels.

It does this on two levels of abstraction which may be redundant and is deserving of critical review. The reason for this is there is non-trivial message construction is happening in `ManagedLogger` but to me changing `AbstractLogger` would offer a more general solution for all types of loggers.

Lastly, I upgraded the versions of scala as well as the scalafmt plugin.

2017-11-07 08:53 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?util=pull/131/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

2017-11-07 10:46 UTC, dwijnand approved these changes
LGTM. Thank you @leonardehrenfried.

2017-11-07 19:50 UTC, eed3si9n requested changes
This goes against the current design of sbt logging.
In sbt 1 the logger doesn't fully know whether something should be logged or not since that's determined by the appenders that subscribes to the logger. Making this change would break `last` command.

The log message produced by Ivy (sbt/sbt#3711) I think should be treated as special case since the integration of Ivy logging (via slf4j?) is something new to sbt 1.

2017-11-08 07:34 UTC, leonardehrenfried commented
@eed3si9n Thanks for the review. Do you think that changing https://github.com/sbt/librarymanagement/blob/1.x/ivy/src/main/scala/sbt/internal/librarymanagement/IvyLogger.scala#L25 would be the way forward?

Or should the sbt/util be changed and check the logger name to filter out ivy log events?

2017-11-08 11:45 UTC, leonardehrenfried commented
Closed in favour of #132

2017-11-08 11:49 UTC, closed without merging