Give SourcePosition a macro instance creator
sbt/util pull request #146
Opened 2018-01-29 15:29 UTC by dwijnand

2018-01-29 15:29 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=1.x&io=1.x&librarymanagement=1.x&util=pull/146/head&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

2018-01-31 04:52 UTC, eed3si9n commented
When do I use this?

2018-01-31 08:18 UTC, dwijnand commented
In extreme cases if you want to semi-manually use the `set` method on keys. Instead of passing `NoPosition` you can actually synthesise the position.

2018-02-07 17:33 UTC, eed3si9n requested changes

2018-02-07 17:33 UTC, eed3si9n commented on internal/util-position/src/test/scala/sbt/internal/util/SourcePositionSpec.scala
> +    SourcePosition() match {
This looks like a pure expression, but it actually side effects to the author's machine.
It would be good have another name to signal it's a macro.

2018-02-09 12:38 UTC, merged