Improve xsbti.Maybe
sbt/util pull request #55
Opened 2016-10-31 15:20 UTC by dwijnand

* Make Nothing a singleton
* Make Maybe's constructor private
* Optimise equals to use reference equality first
* Optimise Just.equals by having proper, non-anonymous subclasses
* Having non-anonymous subclasses makes them have nicer classnames
* Give Just a value() method

2016-10-31 15:23 UTC, Duhemm commented on internal/util-interface/src/main/java/xsbti/Maybe.java
> +  public static final class Nothing extends Maybe<Object> {
I think the best way to implement singleton in Java is to use `enum`s?

2016-10-31 15:24 UTC, dwijnand commented
Optimised for reviewing with whitespace changes removed: https://github.com/sbt/util/pull/55/files?w=1

2016-10-31 15:30 UTC, xuwei-k requested changes

2016-10-31 15:30 UTC, xuwei-k commented on internal/util-interface/src/main/java/xsbti/Maybe.java
> +      if (o == null || o instanceof Just<?>) return false;
```java
if (o == null || !(o instanceof Just<?>)) return false;
```

2016-10-31 15:37 UTC, dwijnand commented on internal/util-interface/src/main/java/xsbti/Maybe.java
> +      if (o == null || o instanceof Just<?>) return false;
Thank you Yoshida-san

2016-10-31 15:38 UTC, dwijnand commented on internal/util-interface/src/main/java/xsbti/Maybe.java
> +  public static final class Nothing extends Maybe<Object> {
enum's can't extend classes and I don't want to make Maybe an interface

2016-11-15 17:15 UTC, dwijnand commented
I'm sure if there's a problem here we can forward-fix or revert.

2016-11-15 17:15 UTC, merged